steps:
  - label: ":brain: Everything"
    env:
      SEGMENT_BUILDKITE_IMAGE: "buildkite-agent-golang1.18"
    agents:
      queue: v1
    commands: |
      export GO111MODULE=on

      echo '--- Vendoring dependencies'
      go mod tidy
      go mod vendor
      if [ "$(git status --porcelain)" != "" ]; then
        echo "git tree is dirty after tidying and vendoring modules"
        echo "ensure go.mod and go.sum are tidy and vendor is checked in"
        git status
        exit 1
      fi

      echo '--- Building  package'
      go build -v

      echo '--- Running tests'
      go test -v

  - wait: ~
